export default [
  {
    id: 1,
    name: "Áo Bóng Đá CLB Manchester United Sân Nhà",
    image: require("../Anh/aoMU.jpg"),
    price: "150000",
    rating: 4.5,
    detail: "Dùng khi thi đấu ở sân nhà",
  },
  {
    id: 2,
    name: "Áo Bóng Đá CLB Manchester United Sân Khách",
    image: require("../Anh/aomukhach.jpg"),
    price: "150000",
    rating: 4.5,
    detail: "Dùng khi thi đấu ở sân khách",
  },
  {
    id: 3,
    name: "Áo Bóng Đá CLB Manchester City Sân Nhà",
    image: require("../Anh/aomancity.jpg"),
    price: "150000",
    rating: 4.5,
    detail: "Dùng khi thi đấu ở sân nhà",
  },
  {
    id: 4,
    name: "Áo Bóng Đá CLB Manchester City Sân Khách",
    image: require("../Anh/aomancitykhach.jpg"),
    price: "150000",
    rating: 4.5,
    detail: "Dùng khi thi đấu ở sân khách",
  },
  {
    id: 5,
    name: "Áo Bóng Đá CLB Manchester United Thứ 3",
    image: require("../Anh/aomu3.jpg"),
    price: "150000",
    rating: 4.5,
    detail: "Áo đấu thứ 3 dùng khi thi đấu",
  },
  {
    id: 6,
    name: "Áo Bóng Đá CLB Real Madrid Sân Nhà",
    image: require("../Anh/aoreal.jpg"),
    price: "150000",
    rating: 4.5,
    detail: "Dùng khi thi đấu ở sân nhà",
  },
];
